apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: du02gkjpj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: du02gkjpj-python 
  name: du02gkjpj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: du02gkjpj-python 
